### ISSUE TITLE
logBackendError broken

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#748] opened 2015-02-19 09:32 UTC
`Http.Error.logBackendError` regularly breaks itself instead of showing an error. This makes debugging harder instead of improving it.

Example: Open an non-existing page such as http://localhost:6551/r/principals/users/00000i

**Comment by xi** [comment] 2015-02-20 11:11
> Example: Open an non-existing page such as http://localhost:6551/r/principals/users/00000i

This particular case is probably caused by #256. Still, I would also appreciate a fix in the frontend.

**Comment by xi** [comment] 2015-09-21 09:27
Fixed by #1445 (68f1332)

**Closed by xi** 2015-09-21 09:27 UTC
Labels: bug, frontend, low prio
