### ISSUE TITLE
Comment rate + edit broken

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#804] opened 2015-02-24 16:12 UTC
Steps to reproduce:

-  create a comment
-  rate that comment
-  edit that comment

Expected result:

-  rate counter shows 1

Actual result:

-  rate counter shows 0

**Comment by xi** [comment] 2015-02-24 16:12
might be connected to #803

**Comment by nidico** [comment] 2015-02-26 01:56
I think this is caused by two issues - one in the frontend and one in the backend:

- The frontend doesn't update a comment resource after editing - i.e. we still show the old comment path (and thus rating). This is because the comment resource (one item in the listing) is an *item*, not a *version*, and calling `$scope.update` on the listing doesn't cause the comment to update.

- The backend doesn't seem to invalidate `LAST` tags, i.e. after creating a new version, the backend returns a 304 when asking for `LAST` and thus still points to the old version.

**Comment by xi** [comment] 2015-03-02 13:20
> This is because the comment resource (one item in the listing) is an item, not a version

See #192 on why it is implemented like that.

**Comment by nidico** [comment] 2015-03-02 20:43
This isn't fixed yet - 53e8c8f fixed #820, a backend issue with similar symptoms.

**Comment by joka** [comment] 2015-03-03 10:10
@nidico should in investigate if this is a backend issue?

**Comment by nidico** [comment] 2015-03-03 11:06
> @nidico should I investigate if there is still a backend issue?

@joka: No, #804 is a frontend issue, which is supposed to be fixed with #838.

#820 is the backend issue, which you have already fixed.

**Closed** 2015-03-03 11:40 UTC
Labels: bug, frontend, high prio
