### ISSUE TITLE
Going from detail column overlay (report, share etc) to edit view. Mask still visible.

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3.mercator#650] opened 2015-02-05 11:55 UTC
![download 1](https://cloud.githubusercontent.com/assets/701632/6059800/1c24df02-ad36-11e4-9047-f0a6d36aa11e.png)

**Comment by nidico** [comment] 2015-02-05 13:12
This is part of #577.

**Comment by local-girl** [comment] 2015-02-05 13:14
Kind of but it's also a UI bug ?

**Comment by nidico** [comment] 2015-02-05 13:17
I thought that if the overlay closed on view mode change, the UI would automatically adapt and remove the mask.

**Comment by local-girl** [comment] 2015-02-05 13:21
Yes I suppose so. I have some comments on #577 then...

**Comment by xi** [comment] 2015-02-09 09:30
Agree with @nidico: This is a duplicate of #577.

**Closed by xi** 2015-02-09 09:30 UTC
Labels: bug, frontend, ui
