### ISSUE TITLE
Brower autofill not recognized by angular

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#878] opened 2015-03-10 15:35 UTC
When the brower autofills a form, the change is not (necessarily) detected by angular. This is especially annoying on the login form.

@ChristianSi reported this using firefox/iceweasel on debian testing.

~~@nidico says he thought he had this fixed.~~

**Comment by nidico** [comment] 2015-03-10 15:40
I thought that we're talking about login issues which have been fixed in #765 / #771, though autofill wasn't involved here. We should focus our investigation on this.

**Comment by nidico** [comment] 2015-03-10 16:08
@ChristianSi says this can be reproduced: Using autofill in iceweasel 31.5.0 from debian testing leads to the login-submit-button being disabled. If a letter is then appended to each username and password, the button is enabled.

I can't reproduce this in Firefox 36 on Fedora.

**Comment by xi** [comment] 2015-03-10 17:24
Can reproduce

**Comment by xi** [comment] 2015-03-10 17:31
There is a longish (and now locked) discussion about this on https://github.com/angular/angular.js/issues/1460 that mentions https://github.com/tbosch/autofill-event as a possible workaround. Further evaluation needed.

**Closed** 2015-03-16 17:05 UTC
Labels: bug, frontend
