### ISSUE TITLE
Invalid title on the messaging window

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#749] opened 2015-02-19 13:23 UTC
When writing a message to a user, by clicking the "mail" button on a user's page, the title above the 'subject' and 'content' field is "Message to Username" instead of "Message to &lt;Username&gt;". The username is not replaced in the text.

**Comment by xi** [comment] 2015-02-20 11:08
duplicate of #702.

**Closed by xi** 2015-02-20 11:08 UTC
Labels: duplicate
