### ISSUE TITLE
Incomplete input validation for IPoint

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1484] opened 2015-07-29 13:11 UTC
It is possible to create a `adhocracy_core.sheets.geo.IPoint` sheet like this:

```
{coordinates: [null, null]}
```

This will not give an issue on POST but trying to GET the created resource results in the following error message:

```
{
  errors: [{
    description: "\"<colander._drop object at 0x7f67f0d16e48>\" is not a number"
    location: "body"
    name: "coordinates.0"
  }, {
    description: "\"<colander._drop object at 0x7f67f0d16e48>\" is not a number"
    location: "body"
    name: "coordinates.1"
  }],
 status: "error"
}
```

**Comment by pallix** [comment] 2015-07-29 13:19
Duplicate of #1081 concerning the backend

**Closed** 2015-07-29 13:21 UTC
Labels: backend, bug, upstream
